# train_model.py

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib
import os

# 1. Sample dataset
data = pd.DataFrame([
    {
        "name": "Arvind Chawla",
        "age": 30,
        "gender": "Male",
        "height": "5.9\"",
        "weight": 75,
        "bloodPressure": "120/90 mmHg",
        "bloodSugarPP": "130 mg/dL",
        "hemoglobin": "13.5 g/dL",
        "wbcCount": "6500 /µL",
        "platelets": "2.4 lakh /µL",
        "creatinine": "1.0 mg/dL",
        "urea": "18 mg/dL",
        "sgpt": "22 / 28 U/L",
        "sgot": "22 / 28 U/L",
        "totalCholesterol": "180 mg/dL",
        "hdl": "55 mg/dL",
        "ldl": "95 mg/dL",
        "triglycerides": "135 mg/dL",
        "tsh": "2.1 µIU/mL",
        "vitaminD": "32 ng/mL",
        "vitaminB12": "450 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Rajendra",
        "age": 32,
        "gender": "Male",
        "height": "5.8\"",
        "weight": 80,
        "bloodPressure": "123/93 mmHg",
        "bloodSugarPP": "132 mg/dL",
        "hemoglobin": "13.6 g/dL",
        "wbcCount": "6600 /µL",
        "platelets": "2.5 lakh /µL",
        "creatinine": "1.1 mg/dL",
        "urea": "19 mg/dL",
        "sgpt": "23 / 29 U/L",
        "sgot": "23 / 29 U/L",
        "totalCholesterol": "190 mg/dL",
        "hdl": "56 mg/dL",
        "ldl": "96 mg/dL",
        "triglycerides": "136 mg/dL",
        "tsh": "2.2 µIU/mL",
        "vitaminD": "33 ng/mL",
        "vitaminB12": "455 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Vivek",
        "age": 38,
        "gender": "Male",
        "height": "5.10\"",
        "weight": 70,
        "bloodPressure": "126/96 mmHg",
        "bloodSugarPP": "134 mg/dL",
        "hemoglobin": "13.7 g/dL",
        "wbcCount": "6700 /µL",
        "platelets": "2.6 lakh /µL",
        "creatinine": "1.2 mg/dL",
        "urea": "20 mg/dL",
        "sgpt": "24 / 30 U/L",
        "sgot": "24 / 30 U/L",
        "totalCholesterol": "200 mg/dL",
        "hdl": "57 mg/dL",
        "ldl": "97 mg/dL",
        "triglycerides": "137 mg/dL",
        "tsh": "2.3 µIU/mL",
        "vitaminD": "34 ng/mL",
        "vitaminB12": "460 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Bablu",
        "age": 34,
        "gender": "Male",
        "height": "6\"",
        "weight": 50,
        "bloodPressure": "129/99 mmHg",
        "bloodSugarPP": "136 mg/dL",
        "hemoglobin": "13.8 g/dL",
        "wbcCount": "6800 /µL",
        "platelets": "2.7 lakh /µL",
        "creatinine": "1.3 mg/dL",
        "urea": "21 mg/dL",
        "sgpt": "26 / 32 U/L",
        "sgot": "26 / 32 U/L",
        "totalCholesterol": "210 mg/dL",
        "hdl": "58 mg/dL",
        "ldl": "98 mg/dL",
        "triglycerides": "138 mg/dL",
        "tsh": "2.4 µIU/mL",
        "vitaminD": "35 ng/mL",
        "vitaminB12": "465 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Sonam",
        "age": 26,
        "gender": "Male",
        "height": "5.6\"",
        "weight": 60,
        "bloodPressure": "131/96 mmHg",
        "bloodSugarPP": "138 mg/dL",
        "hemoglobin": "13.9 g/dL",
        "wbcCount": "6900 /µL",
        "platelets": "2.8 lakh /µL",
        "creatinine": "1.4 mg/dL",
        "urea": "22 mg/dL",
        "sgpt": "28 / 34 U/L",
        "sgot": "28 / 34 U/L",
        "totalCholesterol": "220 mg/dL",
        "hdl": "59 mg/dL",
        "ldl": "99 mg/dL",
        "triglycerides": "139 mg/dL",
        "tsh": "2.5 µIU/mL",
        "vitaminD": "36 ng/mL",
        "vitaminB12": "470 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Ravi Singh",
        "age": 40,
        "gender": "Male",
        "height": "5.7\"",
        "weight": 72,
        "bloodPressure": "128/88 mmHg",
        "bloodSugarPP": "140 mg/dL",
        "hemoglobin": "14.1 g/dL",
        "wbcCount": "7000 /µL",
        "platelets": "2.9 lakh /µL",
        "creatinine": "1.2 mg/dL",
        "urea": "23 mg/dL",
        "sgpt": "27 / 33 U/L",
        "sgot": "27 / 33 U/L",
        "totalCholesterol": "230 mg/dL",
        "hdl": "60 mg/dL",
        "ldl": "100 mg/dL",
        "triglycerides": "140 mg/dL",
        "tsh": "2.6 µIU/mL",
        "vitaminD": "37 ng/mL",
        "vitaminB12": "475 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Amit Sharma",
        "age": 35,
        "gender": "Male",
        "height": "5.9\"",
        "weight": 78,
        "bloodPressure": "124/84 mmHg",
        "bloodSugarPP": "129 mg/dL",
        "hemoglobin": "14.2 g/dL",
        "wbcCount": "7100 /µL",
        "platelets": "3.0 lakh /µL",
        "creatinine": "1.1 mg/dL",
        "urea": "17 mg/dL",
        "sgpt": "25 / 31 U/L",
        "sgot": "25 / 31 U/L",
        "totalCholesterol": "185 mg/dL",
        "hdl": "54 mg/dL",
        "ldl": "94 mg/dL",
        "triglycerides": "132 mg/dL",
        "tsh": "2.0 µIU/mL",
        "vitaminD": "31 ng/mL",
        "vitaminB12": "445 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Pooja Sinha",
        "age": 29,
        "gender": "Female",
        "height": "5.4\"",
        "weight": 58,
        "bloodPressure": "118/82 mmHg",
        "bloodSugarPP": "110 mg/dL",
        "hemoglobin": "13.2 g/dL",
        "wbcCount": "6400 /µL",
        "platelets": "2.6 lakh /µL",
        "creatinine": "0.9 mg/dL",
        "urea": "16 mg/dL",
        "sgpt": "20 / 26 U/L",
        "sgot": "20 / 26 U/L",
        "totalCholesterol": "170 mg/dL",
        "hdl": "52 mg/dL",
        "ldl": "90 mg/dL",
        "triglycerides": "128 mg/dL",
        "tsh": "1.9 µIU/mL",
        "vitaminD": "30 ng/mL",
        "vitaminB12": "435 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Rakesh Gupta",
        "age": 41,
        "gender": "Male",
        "height": "5.11\"",
        "weight": 82,
        "bloodPressure": "138/92 mmHg",
        "bloodSugarPP": "143 mg/dL",
        "hemoglobin": "13.4 g/dL",
        "wbcCount": "7300 /µL",
        "platelets": "3.1 lakh /µL",
        "creatinine": "1.4 mg/dL",
        "urea": "24 mg/dL",
        "sgpt": "30 / 35 U/L",
        "sgot": "30 / 35 U/L",
        "totalCholesterol": "240 mg/dL",
        "hdl": "61 mg/dL",
        "ldl": "101 mg/dL",
        "triglycerides": "141 mg/dL",
        "tsh": "2.7 µIU/mL",
        "vitaminD": "38 ng/mL",
        "vitaminB12": "480 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    },
    {
        "name": "Sneha Kapoor",
        "age": 28,
        "gender": "Female",
        "height": "5.5\"",
        "weight": 62,
        "bloodPressure": "117/79 mmHg",
        "bloodSugarPP": "108 mg/dL",
        "hemoglobin": "13.0 g/dL",
        "wbcCount": "6200 /µL",
        "platelets": "2.3 lakh /µL",
        "creatinine": "0.8 mg/dL",
        "urea": "15 mg/dL",
        "sgpt": "19 / 24 U/L",
        "sgot": "19 / 24 U/L",
        "totalCholesterol": "165 mg/dL",
        "hdl": "50 mg/dL",
        "ldl": "85 mg/dL",
        "triglycerides": "125 mg/dL",
        "tsh": "1.8 µIU/mL",
        "vitaminD": "29 ng/mL",
        "vitaminB12": "430 pg/mL",
        "urineProtein": "Negative",
        "urineGlucose": "Negative",
        "symptoms": "",
        "knownIssues": "",
        "ecgResult": "Normal Sinus"
    }
]
)

# 2. Features and target
X = data.drop("fit", axis=1)
y = data["fit"]

# 3. Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 4. Train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# 5. Save model to predictor/model/fitness_model.pkl
output_dir = os.path.join("predictor", "model")
os.makedirs(output_dir, exist_ok=True)  # Create folder if it doesn't exist

model_path = os.path.join(output_dir, "fitness_model.pkl")
joblib.dump(model, model_path)

print(f"✅ Model trained and saved to: {model_path}")
